//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Sales.Backend.Presenters.ExceptionHandlers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.Sales.Backend.Presenters.ExceptionHandlers.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulte al administrador..
        /// </summary>
        internal static string UnhandledExceptionDetails {
            get {
                return ResourceManager.GetString("UnhandledExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio no se encuentra disponible..
        /// </summary>
        internal static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontraron uno o más errores de actualizacion de datos. Consulte al administrador..
        /// </summary>
        internal static string UnitOfWorkExceptionDetail {
            get {
                return ResourceManager.GetString("UnitOfWorkExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de actualizacion..
        /// </summary>
        internal static string UnitOfWorkExceptionTitle {
            get {
                return ResourceManager.GetString("UnitOfWorkExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontraron uno o mas errores de validacion.
        /// </summary>
        internal static string ValidationExceptionDetail {
            get {
                return ResourceManager.GetString("ValidationExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en los datos de entrada..
        /// </summary>
        internal static string ValidationExceptionTitle {
            get {
                return ResourceManager.GetString("ValidationExceptionTitle", resourceCulture);
            }
        }
    }
}
